steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/quickstart-image', '.' ]
images:
- 'gcr.io/$PROJECT_ID/quickstart-image'
#steps:
# Deploy an image from Container Registry to Cloud Run
#- name: 'gcr.io/cloud-builders/gcloud'
#  args: ['beta', 'run', 'deploy', 'Kojis', '--image', 'gcr.io/kojelauta/quickstart-image', '--region', europe-west1, '--platform', 'managed', '--allow-unauthenticated']
#steps:
# Build the container image
#- name: 'gcr.io/cloud-builders/docker'
#  args: ['build', '-t', 'gcr.io/kojelauta/quickstart-image', '.']
# Push the container image to Container Registry
#- name: 'gcr.io/cloud-builders/docker'
#  args: ['push', 'gcr.io/kojelauta/quickstart-image]']
# Deploy container image to Cloud Run
#- name: 'gcr.io/cloud-builders/gcloud'
#  args: ['beta', 'run', 'deploy', 'Kojis', '--image', 'gcr.io/kojelauta/quickstart-image', '--region', 'europe-west1', '--platform', 'managed', '--allow-unauthenticated']
#  images:
#          - gcr.io/kojelauta/quickstart-image

